export const productionPillars = [
  {
    id: 'observability',
    title: 'Observability Out of the Box',
    icon: 'bi-bar-chart-line',
    description: 'Spring Boot Actuator + Micrometer ship with first-class JaiClaw metrics. Wire to Prometheus and Grafana in minutes.',
    highlights: [
      { label: 'jaiclaw.agent.invocations', detail: 'Counter — agent calls per tenant, provider, outcome' },
      { label: 'jaiclaw.tool.calls', detail: 'Counter — tool invocations per tool, outcome' },
      { label: 'jaiclaw.tokens.usage', detail: 'Counter — prompt / completion / total tokens per provider' },
      { label: 'jaiclaw.sessions.active', detail: 'Gauge — live sessions per tenant' },
    ],
  },
  {
    id: 'kubernetes',
    title: 'Kubernetes-Native Deployment',
    icon: 'bi-box-seam',
    description: 'Reference Helm charts and Kubernetes manifests cover the production basics so you can deploy with confidence.',
    highlights: [
      { label: 'Helm Charts', detail: 'Reference chart for the framework itself' },
      { label: 'Liveness Probe', detail: '/actuator/health/liveness wired up' },
      { label: 'Readiness Probe', detail: '/actuator/health/readiness wired up' },
      { label: 'Prometheus Scrape', detail: 'Scrape annotations on the service' },
    ],
  },
  {
    id: 'multi-tenancy',
    title: 'Multi-Tenancy at the Core',
    icon: 'bi-building',
    description: 'JWT-based tenant isolation is not a layer you add — it is wired through sessions, memory, skills, tools, and billing.',
    highlights: [
      { label: 'JWT-Derived Context', detail: 'Tenant identity flows from auth tokens' },
      { label: 'Per-Tenant Resources', detail: 'Sessions, memory, skills, and tool grants per tenant' },
      { label: 'Billing-Linked Access', detail: 'Feature grants on payment, revoke on expiry' },
      { label: 'Auditability', detail: 'Tenant tag on every metric, log, and audit event' },
    ],
  },
  {
    id: 'security',
    title: 'Security Hardening',
    icon: 'bi-shield-check',
    description: 'Six opt-in protections, agent-to-agent ECDH key exchange, workspace path boundaries, and timing-safe auth comparisons.',
    highlights: [
      { label: 'HMAC Webhooks', detail: 'Verify channel and integration callbacks' },
      { label: 'SSRF Guards', detail: 'Outbound HTTP filter for tool calls' },
      { label: 'Workspace Boundaries', detail: 'File tools cannot escape declared workspace' },
      { label: 'ECDH P-256', detail: 'Agent-to-agent session bootstrap' },
    ],
  },
  {
    id: 'compliance',
    title: 'GDPR + HIPAA Compliance',
    icon: 'bi-file-earmark-lock',
    description: 'A jaiclaw-compliance module wires GDPR + HIPAA safeguards on demand. Compliance-capable framework, not a certified product — both regulations are properties of a deployment. One property (jaiclaw.compliance.profile) toggles a coherent bundle of protections.',
    highlights: [
      { label: 'LLM-Call Audit Trail', detail: 'Every model.inference.request records recipient, data categories, lawful basis, consent token — Art. 30 RoPA reconstructs from the stream' },
      { label: 'BAA-Eligible Providers', detail: 'Bedrock, Azure OpenAI, Vertex AI, Ollama classified BAA-eligible by default; PHI tenant on non-BAA route triggers a warning' },
      { label: 'Retention Enforcement', detail: 'Scheduled purge of transcripts + audit per per-tenant TTL — HIPAA §164.316(b)(2) 6-year audit floor supported' },
      { label: 'HTTPS Startup Guard', detail: 'Refuses to start on a public bind without TLS when any compliance profile is active' },
      { label: 'Data Subject Rights', detail: 'DataSubjectErasureSpi (Art. 17 cascade delete) + /api/gdpr/export/{id} (Art. 15, 20) shipped as Tier 2 SPIs' },
      { label: 'PHI Redaction + AES-GCM', detail: 'PromptRedactor SPI masks PHI/PII before LLM dispatch; FieldEncryptor decorators encrypt transcripts + audit at rest' },
      { label: 'Tamper-Evident Audit', detail: 'HashChainedAuditLogger stamps prevHash + chainHash on every event; verifyChain() reports the first break' },
      { label: 'Governance SPIs (Tier 3)', detail: 'RopaGenerator, ObjectionService (Art. 21), AnomalyDetector, ProcessorMetadataExporter — auto-wired when profile is active' },
    ],
  },
  {
    id: 'api-stability',
    title: 'API Stability Program',
    icon: 'bi-bookmark-check',
    description: '@Stable / @Experimental / @Internal annotations mark every SPI. As of 1.0, 20+ SPIs carry a compatibility guarantee — you know exactly what you can depend on.',
    highlights: [
      { label: '@Stable', detail: 'Semver compatibility guarantee through the 1.x line' },
      { label: '@Experimental', detail: 'Shipping, but may change with notice' },
      { label: '@Internal', detail: 'Do not depend on these — subject to change without notice' },
      { label: '1.0 GA', detail: 'First stable release — API contract locked in' },
    ],
  },
  {
    id: 'sizing',
    title: 'Resource Sizing Guidance',
    icon: 'bi-cpu',
    description: 'Reference deployment profiles for small, medium, and large workloads — with concrete starting points instead of guesswork.',
    highlights: [
      { label: 'Small', detail: 'Single-tenant prototype / internal tool' },
      { label: 'Medium', detail: 'Multi-tenant SaaS up to dozens of tenants' },
      { label: 'Large', detail: 'High-throughput enterprise deployments' },
      { label: 'Tuning Knobs', detail: 'Compaction threshold, session TTL, tool concurrency' },
    ],
  },
];
