export const categories = [
  'All',
  'Getting Started',
  'Pipelines',
  'Business Workflows',
  'Scheduling & Automation',
  'GOAP Multi-Agent',
  'Documents & Knowledge',
  'Communication & Voice',
  'Security',
  'Developer Tools',
  'Local LLM',
  'Apache Camel',
];

export const examples = [
  {
    name: 'daily-briefing',
    title: 'Daily Briefing',
    category: 'Scheduling & Automation',
    description: 'Scheduled morning briefing at 7 AM with news and weather, delivered to Telegram and Email.',
    modules: ['Cron', 'Telegram', 'Email'],
  },
  {
    name: 'sales-report',
    title: 'Sales Report',
    category: 'Scheduling & Automation',
    description: 'Weekly sales dashboard generated every Monday with HTML report via Canvas module.',
    modules: ['Cron', 'Canvas'],
  },
  {
    name: 'price-monitor',
    title: 'Price Monitor',
    category: 'Scheduling & Automation',
    description: 'Hourly price checker monitoring product pages with SMS alerts when prices drop.',
    modules: ['Cron', 'Browser', 'SMS'],
  },
  {
    name: 'system-monitor',
    title: 'System Monitor',
    category: 'Scheduling & Automation',
    description: 'Daily server health analysis with automatic Telegram reporting.',
    modules: ['Cron', 'Telegram'],
  },
  {
    name: 'code-review-bot',
    title: 'Code Review Bot',
    category: 'GOAP Multi-Agent',
    description: 'GOAP-orchestrated PR code review — analyzes diffs and generates structured reviews.',
    modules: ['Embabel', 'Canvas', 'Plugin'],
  },
  {
    name: 'travel-planner',
    title: 'Travel Planner',
    category: 'GOAP Multi-Agent',
    description: 'Multi-step trip planning with parallel flight/hotel search and budget analysis.',
    modules: ['Embabel', 'Browser', 'Voice'],
  },
  {
    name: 'compliance-checker',
    title: 'Compliance Checker',
    category: 'GOAP Multi-Agent',
    description: 'Document compliance verification — extracts policy rules and checks target documents.',
    modules: ['Embabel', 'Documents', 'Audit'],
  },
  {
    name: 'incident-responder',
    title: 'Incident Responder',
    category: 'GOAP Multi-Agent',
    description: 'DevOps incident triage with Kubernetes health checks and automated remediation.',
    modules: ['Embabel', 'K8s Tools'],
  },
  {
    name: 'data-pipeline',
    title: 'Data Pipeline',
    category: 'GOAP Multi-Agent',
    description: 'ETL orchestrator with schema validation and approval workflows.',
    modules: ['Embabel', 'Documents'],
  },
  {
    name: 'document-qa',
    title: 'Document Q&A',
    category: 'Documents & Knowledge',
    description: 'PDF ingestion and semantic search Q&A with citations.',
    modules: ['Documents', 'Memory', 'Compaction'],
  },
  {
    name: 'telegram-docstore',
    title: 'Telegram DocStore',
    category: 'Documents & Knowledge',
    description: 'Telegram bot for document management and semantic search.',
    modules: ['DocStore', 'Telegram'],
  },
  {
    name: 'research-assistant',
    title: 'Research Assistant',
    category: 'Documents & Knowledge',
    description: 'Multi-source research with structured report generation.',
    modules: ['Documents', 'Browser'],
  },
  {
    name: 'content-pipeline',
    title: 'Content Pipeline',
    category: 'Documents & Knowledge',
    description: 'Multi-modal content analysis with plugin-based processing.',
    modules: ['Media', 'Documents', 'Plugin'],
  },
  {
    name: 'meeting-assistant',
    title: 'Meeting Assistant',
    category: 'Communication & Voice',
    description: 'Meeting transcription and summary with speaker identification, delivered to Slack.',
    modules: ['Voice', 'Identity', 'Slack'],
  },
  {
    name: 'helpdesk-bot',
    title: 'Helpdesk Bot',
    category: 'Communication & Voice',
    description: 'Multi-tenant support bot with FAQ search and ticket creation.',
    modules: ['Gateway', 'Security'],
  },
  {
    name: 'voice-call-demo',
    title: 'Voice Call Demo',
    category: 'Communication & Voice',
    description: 'Twilio telephony with outbound reminders and inbound customer service.',
    modules: ['Voice Call', 'Twilio'],
  },
  {
    name: 'security-handshake',
    title: 'Security Handshake',
    category: 'Security',
    description: 'LLM-driven ECDH key exchange and session token bootstrap between agents.',
    modules: ['Tools Security'],
  },
  {
    name: 'security-handshake-server',
    title: 'Security Handshake Server',
    category: 'Security',
    description: 'MCP server implementing full ECDH P-256 security handshake protocol.',
    modules: ['Tools Security', 'MCP'],
  },
  {
    name: 'oauth-provider-demo',
    title: 'OAuth Provider Demo',
    category: 'Security',
    description: 'OAuth-gated LLM access with PKCE and device code flows.',
    modules: ['Identity'],
  },
  {
    name: 'code-scaffolder',
    title: 'Code Scaffolder',
    category: 'Developer Tools',
    description: 'Project scaffolding agent that generates complete project structures.',
    modules: ['Code', 'Plugin'],
  },
  {
    name: 'canvas-dashboard',
    title: 'Canvas Dashboard',
    category: 'Developer Tools',
    description: 'On-demand interactive HTML dashboards with Chart.js visualizations.',
    modules: ['Canvas'],
  },
  {
    name: 'mcp-docs-server',
    title: 'MCP Docs Server',
    category: 'Developer Tools',
    description: 'MCP server exposing JaiClaw documentation as resources with search.',
    modules: ['Docs', 'Gateway'],
  },
  {
    name: 'gemma4-local',
    title: 'Gemma 4 Local',
    category: 'Local LLM',
    description: 'Gemma 4 chatbot running fully local via Ollama with function calling.',
    modules: ['Ollama', 'Gateway'],
  },
  {
    name: 'camel-html-summarizer',
    title: 'Camel HTML Summarizer',
    category: 'Apache Camel',
    description: 'HTML page summarization via Apache Camel routes.',
    modules: ['Camel', 'Documents'],
  },
  {
    name: 'camel-html-summarizer-telegram',
    title: 'Camel HTML Summarizer (Telegram)',
    category: 'Apache Camel',
    description: 'HTML summarizer with Telegram delivery via Camel routes.',
    modules: ['Camel', 'Telegram'],
  },
  {
    name: 'camel-html-summarizer-embabel',
    title: 'Camel HTML Summarizer (Embabel)',
    category: 'Apache Camel',
    description: 'HTML summarizer with Embabel GOAP orchestration.',
    modules: ['Camel', 'Embabel'],
  },
  {
    name: 'camel-pdf-filler',
    title: 'Camel PDF Filler',
    category: 'Apache Camel',
    description: 'PDF form filling via Apache Camel routes.',
    modules: ['Camel', 'Documents'],
  },
  {
    name: 'camel-pdf-filler-telegram',
    title: 'Camel PDF Filler (Telegram)',
    category: 'Apache Camel',
    description: 'PDF form filling with Telegram integration via Camel.',
    modules: ['Camel', 'Telegram', 'Documents'],
  },
  {
    name: 'hello-world',
    title: 'Hello World',
    category: 'Getting Started',
    description: 'Minimal ~30 LOC JaiClaw app — the fastest path from zero to a working agent.',
    modules: ['Starter'],
  },
  {
    name: 'pipeline-e2e',
    title: 'Pipeline E2E',
    category: 'Pipelines',
    description: 'End-to-end declarative pipeline demonstrating classify → route → respond stages.',
    modules: ['Pipeline'],
  },
  {
    name: 'support-triage-pipeline',
    title: 'Support Triage Pipeline',
    category: 'Pipelines',
    description: 'Multi-stage support ticket triage with classification, routing, and reply drafting.',
    modules: ['Pipeline', 'Documents'],
  },
  {
    name: 'invoice-processor',
    title: 'Invoice Processor',
    category: 'Pipelines',
    description: 'Declarative invoice extraction, validation, and accounting handoff pipeline.',
    modules: ['Pipeline', 'Documents'],
  },
  {
    name: 'aiops-incident-responder',
    title: 'AIOps Incident Responder',
    category: 'Pipelines',
    description: 'Detect → diagnose → remediate pipeline for production incidents with Kubernetes integration.',
    modules: ['Pipeline', 'K8s Tools'],
  },
  {
    name: 'competitive-intel-briefing',
    title: 'Competitive Intel Briefing',
    category: 'Pipelines',
    description: 'Multi-source competitive research pipeline producing a structured briefing.',
    modules: ['Pipeline', 'Browser', 'Documents'],
  },
  {
    name: 'sales-enrichment-pipeline',
    title: 'Sales Enrichment Pipeline',
    category: 'Pipelines',
    description: 'Lead enrichment with multi-source lookup, scoring, and CRM update stages.',
    modules: ['Pipeline', 'Browser'],
  },
  {
    name: 'contract-reviewer',
    title: 'Contract Reviewer',
    category: 'Pipelines',
    description: 'Pipeline for clause extraction, risk scoring, and reviewer-ready annotations.',
    modules: ['Pipeline', 'Documents'],
  },
  {
    name: 'support-triage',
    title: 'Support Triage',
    category: 'Business Workflows',
    description: 'Customer support triage workflow with category routing and priority scoring.',
    modules: ['Embabel', 'Documents'],
  },
  {
    name: 'procurement-approval',
    title: 'Procurement Approval',
    category: 'Business Workflows',
    description: 'Purchase request workflow with policy checks and human-in-the-loop approvals.',
    modules: ['Embabel', 'Identity'],
  },
  {
    name: 'tax-advisor',
    title: 'Tax Advisor',
    category: 'Business Workflows',
    description: 'Tax document review workflow with deduction discovery and filing checklist.',
    modules: ['Documents', 'Embabel'],
  },
  {
    name: 'onboarding-intake',
    title: 'Onboarding Intake',
    category: 'Business Workflows',
    description: 'New-hire or customer intake workflow with form parsing and downstream provisioning.',
    modules: ['Documents', 'Identity'],
  },
  {
    name: 'agentmind-demo',
    title: 'AgentMind Demo',
    category: 'Getting Started',
    description: 'Runnable end-to-end demo wiring Soul + Memory + Tendencies against a local Anthropic endpoint, with golden-file prompt composition spec.',
    modules: ['AgentMind', 'Soul', 'Memory'],
  },
  {
    name: 'kanban-demo',
    title: 'Kanban Demo',
    category: 'Business Workflows',
    description: 'Canonical task-board demo — custom state graph, agent-backed columns, live SSE event stream, REST/Actuator surface, ASCII board rendering.',
    modules: ['Kanban', 'SSE'],
  },
];
