export const features = [
  {
    id: 'agentic-ai',
    title: 'Agentic AI Runtime',
    icon: 'bi-robot',
    description: 'A Java runtime for the four capabilities that make an AI agentic: break tasks into steps, invoke tools, decide when the first path fails, and remember context. Built on the 8-module blueprint — purpose, prompt, LLM, tools, memory, orchestration, UI, evals — each block backed by inspectable JaiClaw code.',
    highlights: [
      { label: 'Agent Loop', detail: 'Tool-calling loop with context compaction, retries, and typed intermediate results' },
      { label: 'Autonomy Spectrum', detail: 'Human-in-the-loop, human-on-the-loop, or fully autonomous — same runtime' },
      { label: '8-Module Blueprint', detail: 'Every architectural decision mapped to a JaiClaw SPI or starter' },
      { label: 'Multi-Agent Handoff', detail: 'GOAP planning via Embabel with A* search and auto parallelism' },
      { label: 'Memory + Tools + Skills', detail: 'AgentMind memory, 38+ tools, 70+ skills — swap providers with one env var' },
      { label: 'Test & Eval', detail: 'Agent evaluation framework for regression-testing agent behavior' },
    ],
  },
  {
    id: 'channels',
    title: 'Messaging Channels',
    icon: 'bi-chat-dots',
    description: 'Connect your AI assistant to any messaging platform. All channels support local dev mode — no public endpoint needed.',
    highlights: [
      { label: 'Telegram', detail: 'Long polling — 2 min setup' },
      { label: 'Slack', detail: 'Socket Mode — no webhook' },
      { label: 'Discord', detail: 'Gateway WebSocket' },
      { label: 'Email', detail: 'IMAP polling' },
      { label: 'SMS', detail: 'Twilio integration' },
      { label: 'Signal', detail: 'Signal CLI bridge' },
      { label: 'Teams', detail: 'Bot Framework' },
      { label: 'WhatsApp', detail: 'Business Cloud API' },
      { label: 'Google Chat', detail: 'Workspace integration' },
      { label: 'LINE', detail: 'Messaging API' },
      { label: 'Matrix', detail: 'Federated protocol' },
    ],
  },
  {
    id: 'providers',
    title: 'LLM Providers',
    icon: 'bi-cpu',
    description: 'Swap between 11 LLM providers with a single environment variable. No code changes required.',
    highlights: [
      { label: 'Anthropic', detail: 'Claude models' },
      { label: 'OpenAI', detail: 'GPT models' },
      { label: 'Google Gemini', detail: 'Gemini models' },
      { label: 'Ollama', detail: 'Local LLMs' },
      { label: 'AWS Bedrock', detail: 'Managed AI service' },
      { label: 'Azure OpenAI', detail: 'Enterprise deployments' },
      { label: 'DeepSeek', detail: 'DeepSeek models' },
      { label: 'Mistral', detail: 'Mistral models' },
      { label: 'MiniMax', detail: 'MiniMax models' },
      { label: 'Vertex AI', detail: 'Google Cloud AI' },
      { label: 'OCI GenAI', detail: 'Oracle Cloud AI' },
    ],
  },
  {
    id: 'tools',
    title: 'Built-in Tools',
    icon: 'bi-tools',
    description: '38+ tools organized by category: file editing, browser automation (Playwright), Kubernetes monitoring, document analysis, calendar, and more.',
    highlights: [
      { label: 'File Editing', detail: 'Read, write, patch files with workspace boundaries' },
      { label: 'Browser Automation', detail: '8 Playwright tools — navigate, click, type, screenshot' },
      { label: 'Kubernetes', detail: 'Pod health, logs, resource monitoring' },
      { label: 'Documents', detail: 'PDF ingestion, semantic search, Q&A' },
      { label: 'Calendar', detail: 'Event scheduling and management' },
      { label: 'Code Tools', detail: 'Scaffolding, analysis, workspace-bounded execution' },
    ],
  },
  {
    id: 'skills',
    title: 'Skills System',
    icon: 'bi-lightbulb',
    description: '70+ bundled skills loaded from markdown with YAML frontmatter. Create custom skills or use the built-in library.',
    highlights: [
      { label: '70+ Bundled Skills', detail: 'System admin to content generation' },
      { label: 'Markdown Format', detail: 'YAML frontmatter + markdown body' },
      { label: 'Custom Skills', detail: 'Add your own with simple markdown files' },
      { label: 'Skill Profiles', detail: 'Assign skill sets per use case' },
    ],
  },
  {
    id: 'scaffolding',
    title: 'Project Scaffolding',
    icon: 'bi-magic',
    description: 'Spring-Initializr-class project generator. From a ~10-line YAML manifest to a complete runnable Maven project — via a Maven goal, a Spring Shell command, or a conversational skill that walks you through requirements.',
    highlights: [
      { label: '5 Archetypes', detail: 'gateway, embabel, camel, comprehensive, minimal' },
      { label: '3 Entry Points', detail: 'Maven goal · Spring Shell · conversational skill' },
      { label: '~10-line Manifest', detail: 'Name + description required; everything else has defaults' },
      { label: 'Two Parent Modes', detail: 'standalone (spring-boot-starter-parent) or jaiclaw' },
    ],
  },
  {
    id: 'multi-agent',
    title: 'GOAP Multi-Agent Planning',
    icon: 'bi-diagram-3',
    description: 'Embabel integration for deterministic action sequences computed by A* search, with automatic parallelism detection and typed intermediate results.',
    highlights: [
      { label: 'GOAP Planner', detail: 'Goal-Oriented Action Planning via A* search' },
      { label: 'Auto Parallelism', detail: 'Independent actions run concurrently' },
      { label: 'Typed Results', detail: 'Blackboard domain objects as intermediate state' },
      { label: '@Agent Annotations', detail: '@Action, @AchievesGoal, @Condition' },
    ],
  },
  {
    id: 'mcp',
    title: 'MCP: Host & Consume',
    icon: 'bi-plug',
    description: 'First-class Model Context Protocol support — expose any JaiClaw capability (a tool, a document repository, an agent) as a named MCP server mounted at /mcp/{serverName}, and consume external MCP servers from your agents. Two SPIs, six canonical integration patterns, and 22 in-repo providers dogfooding the surface.',
    highlights: [
      { label: 'McpToolProvider SPI', detail: 'Interactive tools the LLM invokes — one server per Spring bean, tenant-aware' },
      { label: 'McpResourceProvider SPI', detail: 'Read-only content (docs, config, datasets) the LLM lists and reads' },
      { label: '6 Design Patterns', detail: 'Direct wrapper, composite service, MCP-to-agent, event-driven, hierarchical, local resource' },
      { label: '22 In-Repo Providers', detail: 'docs, messaging, agentmind-memory, github (12 tools), calendar, kanban, pipeline, and more' },
      { label: 'HTTP / SSE / stdio', detail: 'Three transports; HTTP by default, all share the same provider code' },
      { label: 'Claude Desktop, Cursor, VS Code', detail: 'Any MCP client can browse and invoke tools via /mcp/{server}' },
    ],
  },
  {
    id: 'multi-tenancy',
    title: 'Enterprise Multi-Tenancy',
    icon: 'bi-building',
    description: 'JWT-based tenant isolation at the framework level. Per-tenant sessions, memory, skills, and billing.',
    highlights: [
      { label: 'JWT Isolation', detail: 'Tenant context from auth tokens' },
      { label: 'Per-Tenant Config', detail: 'Sessions, memory, skills per tenant' },
      { label: 'Billing Integration', detail: 'Stripe, PayPal, Telegram Payments' },
      { label: 'Access Control', detail: 'Feature grants on payment, revoke on expiry' },
    ],
  },
  {
    id: 'plugins',
    title: 'Plugin System',
    icon: 'bi-puzzle',
    description: '22 lifecycle hooks — intercept before/after LLM calls, tool execution, message pipeline, session events, and context compaction.',
    highlights: [
      { label: '22 Hooks', detail: 'Full lifecycle interception' },
      { label: 'LLM Hooks', detail: 'Before/after model calls' },
      { label: 'Tool Hooks', detail: 'Before/after tool execution' },
      { label: 'Pipeline Hooks', detail: 'Message and session events' },
    ],
  },
  {
    id: 'security',
    title: 'Security Hardening',
    icon: 'bi-shield-check',
    description: 'Six opt-in protections: HMAC webhook verification, SSRF guards, workspace path boundaries, timing-safe auth, agent-to-agent ECDH key exchange.',
    highlights: [
      { label: 'ECDH P-256', detail: 'Agent-to-agent key exchange' },
      { label: 'JWT Sessions', detail: 'Challenge-response identity verification' },
      { label: 'SSRF Guards', detail: 'Outbound request filtering' },
      { label: 'Audit Trail', detail: 'Full action logging' },
    ],
  },
  {
    id: 'voice',
    title: 'Voice & Telephony',
    icon: 'bi-mic',
    description: 'Real Twilio telephony — outbound calls with TTS, real-time transcription, bidirectional conversation, and DTMF detection.',
    highlights: [
      { label: 'Outbound Calls', detail: 'Text-to-speech phone calls' },
      { label: 'Inbound Calls', detail: 'Real-time transcription' },
      { label: 'Bidirectional', detail: 'Full conversation mode' },
      { label: '4 TTS Providers', detail: 'Multiple voice synthesis options' },
    ],
  },
  {
    id: 'compaction',
    title: 'Context Window Compaction',
    icon: 'bi-arrows-collapse',
    description: 'Conversations never end. The compaction engine transparently summarizes older messages and keeps going. Configurable threshold.',
    highlights: [
      { label: 'Auto Compaction', detail: 'Transparent background summarization' },
      { label: 'Configurable', detail: 'Set threshold per use case' },
      { label: 'Smart Selection', detail: 'Agent decides what to compress' },
      { label: 'Unlimited Context', detail: 'No conversation length limits' },
    ],
  },
  {
    id: 'billing',
    title: 'Subscription Billing',
    icon: 'bi-credit-card',
    description: 'Turn your bot into a SaaS product. A channel-agnostic PaymentProvider SPI with three production implementations — webhook-verified Stripe, PayPal Orders API, and Telegram in-chat invoicing — plus subscription lifecycle, expiry scheduling, and feature-grant access control.',
    highlights: [
      { label: 'Stripe', detail: 'Full subscription lifecycle — Checkout Sessions, signature-verified webhooks, programmatic cancellation' },
      { label: 'PayPal', detail: 'Orders API v2 checkout + opt-in webhook signature verification via PayPal\'s verification endpoint' },
      { label: 'Telegram Payments', detail: 'In-chat invoicing via Bot Payments API — frontend for an underlying provider token (e.g. Stripe Connect)' },
      { label: 'Access Control', detail: 'Grant features on payment, revoke on expiry, per-tenant lifecycle hooks' },
    ],
  },
  {
    id: 'pipelines',
    title: 'Pipelines + Pipeline Studio',
    icon: 'bi-bezier2',
    image: '/images/pipeline-studio.png',
    imageAlt: 'JaiClaw Pipeline Studio — visual drag-and-drop pipeline builder',
    description: 'Compose multi-stage workflows in YAML, in Java with a fluent .then(...) DSL, or visually in Pipeline Studio — same runtime either way. Trigger via REST, watch via Actuator, validated at startup, hookable across the lifecycle. Seven runnable pipeline examples shipped with 1.0.',
    highlights: [
      { label: 'Pipeline Studio (SPA)', detail: 'Visual drag-and-drop React canvas — author pipelines without writing YAML by hand' },
      { label: 'YAML Pipelines', detail: 'Declarative stages, {{input}} / {{stages.*}} / {{pipeline.*}} templates, validated at boot' },
      { label: 'Java DSL', detail: 'Fluent .then(...) builder for programmatic composition — same PipelineDefinition contract' },
      { label: 'Stage Types', detail: 'AGENT (LLM), PROCESSOR (bean), and Camel stages, chainable in any authoring mode' },
      { label: 'Trigger Modes', detail: 'MANUAL, FILE (folder watch), CRON, and CAMEL_URI — pick per pipeline' },
      { label: 'Operational Surface', detail: 'POST /api/pipelines/{id}/trigger gateway + /actuator/pipelines execution tracker' },
    ],
  },
  {
    id: 'cron-manager',
    title: 'Cron Manager App',
    icon: 'bi-clock-history',
    description: 'A standalone Spring Boot Batch 6 application for scheduled agent execution. Kubernetes-ready deployment with a job-monitoring dashboard — no more shoehorning cron logic into your assistant runtime.',
    highlights: [
      { label: 'Standalone Deploy', detail: 'Runs beside your gateway as its own K8s workload — separate scale, separate failure domain' },
      { label: 'Spring Boot Batch 6', detail: 'Retry policy, chunked execution, transactional job repository baked in' },
      { label: 'Job Dashboard', detail: 'Web UI for schedule inspection, run history, and manual re-triggers' },
      { label: 'Pipeline-Aware', detail: 'Schedule any registered pipeline or ad-hoc agent invocation on a cron expression' },
    ],
  },
  {
    id: 'secrets',
    title: 'Secrets Management',
    icon: 'bi-shield-lock',
    description: 'Pluggable SecretsProvider SPI resolves ${VAR} placeholders through Spring PropertySource — swap the backend without touching your config. Environment, file, and 1Password backends ship in the box.',
    highlights: [
      { label: '1Password Backend', detail: 'OnePasswordSecretsProvider — reference vault items directly from application.yml or CLI wizard' },
      { label: 'Env + File Backends', detail: 'EnvironmentSecretsProvider (default) and FileSecretsProvider (.env files) — zero-config for local dev' },
      { label: 'Per-Tenant Prefixing', detail: 'TenantSecretsResolver namespaces secrets so multi-tenant deployments never leak across tenants' },
      { label: 'Transparent Placeholders', detail: 'Existing ${MY_VAR} refs keep working — the provider fronts them via Spring PropertySource' },
    ],
  },
  {
    id: 'camel',
    title: 'Apache Camel Integration',
    icon: 'bi-signpost-split',
    description: 'Drop JaiClaw agents into existing Apache Camel routes — bridge enterprise integration patterns to LLM-powered processing.',
    highlights: [
      { label: 'Camel Routes', detail: 'JaiClaw agent as a Camel endpoint' },
      { label: 'EIP Compatible', detail: 'Splitter, aggregator, filter, router' },
      { label: 'Channel Bridge', detail: 'Camel → Telegram/Slack/Email handoff' },
      { label: 'Embabel Bridge', detail: 'Camel routes invoke GOAP plans' },
    ],
  },
  {
    id: 'i18n',
    title: 'Internationalization',
    icon: 'bi-translate',
    description: '10 built-in locales for prompts, system messages, and channel responses. Add custom locales with simple resource bundles.',
    highlights: [
      { label: '10 Locales', detail: 'Built-in language coverage' },
      { label: 'Prompt Templates', detail: 'Locale-aware system messages' },
      { label: 'Per-Tenant', detail: 'Different locale per tenant' },
      { label: 'Custom Locales', detail: 'Add via resource bundles' },
    ],
  },
  {
    id: 'observability',
    title: 'Production & Observability',
    icon: 'bi-bar-chart-line',
    description: 'Spring Boot Actuator + Micrometer metrics out of the box, with Kubernetes manifests, Helm charts, Prometheus scrape config, and health probes.',
    highlights: [
      { label: 'Micrometer Metrics', detail: 'jaiclaw.agent.invocations, tool.calls, tokens.usage, sessions.active' },
      { label: 'Prometheus', detail: 'Scrape-ready endpoint' },
      { label: 'Kubernetes', detail: 'Helm charts and manifests included' },
      { label: 'Health Probes', detail: 'Liveness + readiness configured' },
    ],
  },
  {
    id: 'api-stability',
    title: 'API Stability Program',
    icon: 'bi-bookmark-check',
    description: '@Stable, @Experimental, and @Internal annotations mark every SPI in the framework. As of 1.0, 20+ SPIs carry a compatibility guarantee — no more guessing which extension points are safe to depend on.',
    highlights: [
      { label: '@Stable', detail: 'Semver compatibility guarantee through the 1.x line' },
      { label: '@Experimental', detail: 'Shipping, but may change with notice' },
      { label: '@Internal', detail: 'Implementation detail — do not depend on' },
      { label: '1.0 GA', detail: 'First stable release — API contract locked in' },
    ],
  },
  {
    id: 'canvas',
    title: 'Canvas & A2UI Dashboards',
    icon: 'bi-window-desktop',
    description: 'Agents render live interactive HTML dashboards on demand — Chart.js visualizations, real-time updates, and Agent-to-UI bidirectional messaging.',
    highlights: [
      { label: 'On-Demand HTML', detail: 'Agent generates dashboards inline' },
      { label: 'Chart.js', detail: 'Built-in chart components' },
      { label: 'A2UI Protocol', detail: 'Bidirectional agent ↔ UI messaging' },
      { label: 'Live Updates', detail: 'Push updates from agent to canvas' },
    ],
  },
  {
    id: 'oauth-rotation',
    title: 'OAuth Credential Rotation',
    icon: 'bi-arrow-repeat',
    description: 'Round-robin across multiple API keys with cooldown tracking — and auto-syncs OAuth tokens from Claude CLI and Codex CLI so local dev just works.',
    highlights: [
      { label: 'Round-Robin Keys', detail: 'Spread load across credentials' },
      { label: 'Cooldown Tracking', detail: 'Back off rate-limited keys automatically' },
      { label: 'Claude CLI Sync', detail: 'Reuse local CLI auth' },
      { label: 'Codex CLI Sync', detail: 'Reuse local CLI auth' },
    ],
  },
  {
    id: 'agentmind',
    title: 'AgentMind: Soul / Memory / Tendencies',
    icon: 'bi-brain',
    description: 'Persistent agent personality, bounded cross-session memory, and per-user behavioral learning — without a vector database. Three opt-in pillars compose into a system prompt the agent helps maintain.',
    highlights: [
      { label: 'Soul', detail: 'Persona overlay (concise / technical / mentor / socratic / pirate) — swap at runtime via the personality tool' },
      { label: 'Memory', detail: 'Single-document markdown memory mutated in-place by the agent, with char-budgeted overflow consolidation' },
      { label: 'Tendencies', detail: 'Per-user communication-style inference — deterministic default, swap to LLM-backed or remote Honcho' },
      { label: 'Opt-In, Multi-Tenant', detail: 'All three pillars off by default; per-agent and per-tenant scoping under JWT isolation' },
    ],
  },
  {
    id: 'kanban',
    title: 'Kanban Task Boards',
    icon: 'bi-kanban',
    description: 'Declarative task boards where columns are agent-backed processors. Custom state graphs, idempotent retries, crash recovery, and live SSE event streams — no external queue or workflow engine.',
    highlights: [
      { label: 'Custom State Graphs', detail: 'Define transitions and side-states (e.g. blocked) per board; the engine enforces the graph' },
      { label: 'Agent Column Processors', detail: 'Fire deterministic or LLM-backed runners on column entry; idempotent via EffectLedger' },
      { label: 'REST + SSE + Actuator', detail: 'Full Spring Boot surface — live board events, board snapshots, metrics' },
      { label: 'Pluggable Stores', detail: 'YAML, H2, JDBC, Redis, Postgres backends; durable per-board transition journal' },
    ],
  },
];

// A small curated set of bundled skills, surfaced on /features as a spotlight
// below the main feature grid. The ascii-rendering entry is special-cased in
// FeaturesView.jsx with a before/after code-block treatment.
export const skillsSpotlight = [
  {
    id: 'ascii-rendering',
    title: 'ascii-rendering',
    icon: 'bi-bounding-box',
    summary: 'Render clean Unicode boxes, diagrams, scatter plots, and tables via the ascii_box and ascii_render tools — instead of hand-drawing borders character-by-character.',
  },
  {
    id: 'systematic-debugging',
    title: 'systematic-debugging',
    icon: 'bi-bug',
    summary: 'Root-cause investigation methodology applied before fixes. Reproduce, isolate, hypothesize, instrument, verify — the agent works the discipline instead of guessing at edits.',
  },
  {
    id: 'k8s-monitoring',
    title: 'k8s-monitoring',
    icon: 'bi-hdd-network',
    summary: 'Kubernetes SRE assistant. Cluster health checks, pod log triage, resource pressure scans, and remediation suggestions, gated behind kubectl.',
  },
  {
    id: 'kanban-orchestrator',
    title: 'kanban-orchestrator',
    icon: 'bi-kanban',
    summary: 'Decompose a goal into kanban work items and route each card through agent-backed column processors. Pairs with the Kanban Task Boards feature for multi-agent coordination.',
  },
  {
    id: 'web-research',
    title: 'web-research',
    icon: 'bi-search',
    summary: 'Multi-source web research and synthesis. Fan out searches, fetch sources, reconcile contradictions, and produce a cited summary — the foundation under the research-assistant example.',
  },
];
